version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm test
      - run: npm build
      - run: npm netlify:deploy
